name: Compare
on:
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0-23/8 * * *'
jobs:

  build:
    strategy:
        matrix:
          golang: [1.15, 1.16]

    name: Smoke
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
    - name: Build docker
      run: |
        docker build .
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3        
